### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [Razzlegames/GodotFireBallExample#1]
It would be useful so that people know to what extent they can base their own scripts or scenes on the examples you have here. If you don't mind much about further usage, you could probably use the MIT license (like Godot's demos) or CC0 ("public domain"-like).

**Comment by Razzlegames** [comment]
Oh darn.  LOL thanks for pointing that out.  I just created this. MIT is fine.

**Comment by Razzlegames** [comment]
Added to wiki :)

**Comment by akien-mga** [comment]
Thanks! :)
